variable "env" {}
variable "tags" {}
variable "subnet_ids" {}
variable "vpc_id" {}
variable "component" {}
variable "port" {}
variable "sg_ingress_cidr" {}
variable "ssh_ingress_cidr" {}
variable "zone_id" {}
variable "instance_type" {}
variable "desired_capacity" {}
variable "max_size" {}
variable "min_size" {}
variable "alb_name" {}