variable "env" {}
variable "tags" {}
variable "vpc_id" {}
variable "port" {}
variable "component" {}
variable "subnet_ids" {}
variable "sg_ingress_cidr" {}
variable "ssh_ingress_cidr" {}
variable "instance_type" {}